# This is a basic workflow to help you get started with Actions

name: MY_CI2

# Controls when the workflow will run
on: push
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print my_testing
        run: echo "my_testing"

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Checkout code
        uses: actions/checkout@v2.5.1

      - name: Set up Java
        uses: actions/setup-java@v2.5.1

        with:
          distribution: 'adopt'
          java-version: '11'

      - name: SonarQube Scan
        run: mvn sonar:sonar -Dsonar.projectKey=a1 -Dsonar.sources=. -Dsonar.host.url=http://31.220.85.178:9001 -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Extract branch name
      #   shell: bash
      #   run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      #   id: extract_branch
